### ISSUE TITLE
Add bibliography

### ISSUE THREAD

**Issue by paulremo** [paulremo/NRPMHandbook#10]
A bibliography is missing from the handbook. The system used to manage the bibliography has been implemented in 144078afe8793edb2046a275433046475943ef52.

To set up the final bibliography, the following should be done:

1. All references from the static handbook should be put into the `references.bib` file
2. We distinguish between **normative** and **bibliographic references**. Each reference hast to assigned **one of those** categories in the `keyword`field:
```
The following is a normative reference:
@article{holdgraf_rapid_2016,
	...
	keywords = {nr}
}
The following is a bibliographic reference:
@article{holdgraf_rapid_2016,
	...
	keywords = {br}
}
```

**Comment by csxADS** [comment]
Where can I find normative references in the document ? What about the RD tags ?

**Comment by paulremo** [comment]
I would say RDs in the original document are the NRs in the digital handbook. I'll double-check asap, but do it like this for now.

**Comment by paulremo** [comment]
Classification for RDs into NRs and BRs has to be discussed. I'll send an email around about this.

**Comment by csxADS** [comment]
Done commit d525e5cc7e773c1ec65b491746f662b5f9b5a561 for misc

**Comment by paulremo** [comment]
Thanks! Did you ever use the `{cite:t}` command to include textual citations? If not, it's not a big issue but something to consider for the final revision of the chapter + the other chapters.

**Comment by csxADS** [comment]
Do I have to use cite t or cite p ?

**Comment by paulremo** [comment]
Depends on the context:
-  `{cite:p}` is a citation in parenthesis, in our citation style, this just inserts a reference in square brackets. This should be used primarily at the end of sentences, i.e., when the reference is not a part of the sentence.
-  `{cite:t}` is a textual citation, in our citation style, this also inserts the first author before the square brackets thereby improving readability. This should be used when a reference is part of a sentence.

Compare the following:

As was shown in *Johnson et. al.* [NR_MIS_12] that the earth is flat. `{cite:t}`
It is well-known that the earth is flat [NR_MIS_12]. `{cite:p}`
