### ISSUE TITLE
Miscellaneous clean-up

### ISSUE THREAD

**Issue by paulremo** [paulremo/NRPMHandbook#15]
Just a few things to clean up before finishing the miscellaneous draft:

- [x] Delete citation tests on https://nrpmhandbook.reliability.space/miscellaneous/handbook/terms.html
- [x] Broken references on https://nrpmhandbook.reliability.space/miscellaneous/handbook/reliability_prediction/ior_results.html
- [x] Broken references on https://nrpmhandbook.reliability.space/miscellaneous/handbook/reliability_prediction/reliability_data_sm.html

**Comment by csxADS** [comment]
Done commit 472841559c189ca2daa96a7d97b0de7f42e1cab1

**Comment by paulremo** [comment]
Thanks 😃!
