### ISSUE TITLE
Miscellaneous chapter review

### ISSUE THREAD

**Issue by paulremo** [paulremo/NRPMHandbook#16]
This is @paulremo's review of the miscellaneous chapter:

I suggest the following changes/improvements (to be discussed):

- [x] Capitalization of titles not consistent (e.g. *Normative References* vs. *Reliability prediction for miscellaneous items* and *Reliability Models for miscellaneous items*); Only capitalize first letter and names (see ECSS);
- [x] Use of «» and "" is not consistent. Use "" (see ECSS);
- [x] Font (serif vs. sans serif fonts) and colors in interactive tables do not match surrounding text - try reusing CSS. Consider to change the color of the tables to a blueish color (color language should be consistent)
- [x] On [this](https://nrpmhandbook.reliability.space/miscellaneous/handbook/reliability_prediction/data_sources_methods.html) page, the sections **statistical data** etc. should go inside drop downs;
- [x] Add bullet points whenever it simplifies comprehension (e.g., [here](https://nrpmhandbook.reliability.space/miscellaneous/handbook/reliability_prediction/reliability_models.html))
- [x] When words or acronyms are used inside equations, use the `\text{}` environment (e.g., replace `P(FAILURE)` with `P(\text{FAILURE})` and `T_{RF}` with `T_{\text{RF}}`);
- [x] Use the `\left` and `\right` marks inside equations to get correct sizes for parantheses;
- [x] The [failure-rate processing model](https://nrpmhandbook.reliability.space/miscellaneous/models/failure_rate_processing.html) is missing a *Go to handbook* button.
- [x] ~Avoid admonitions inside admonitions (there is an ugly space between the nested admonition);~
- [x] Avoid empty/almost empty sections. Task project team to provide text. If no text available, add a **todo admonition** with the following text: _The content of this page is missing and will be provided in a future version of the NRPM digital handbook._
- [x] Don't overuse `*` or `\cdot` inside equations. Do not use `\bullet`! Most of the time these symbols are not required (especially when variables are involved) if necessary, `\cdot` should be preferred;
- [x] Where available, references should include a DOI or at least a URL to improve interactivity;

This is @MatthiasSchubert's review of the miscellaneous chapter:

- [x] In Chapter 5.4 the first sentences (from "This chapter deals with ...... end of the "note") can be moved to the section 5.1 Scope.
- [x] Figure 5.3 and 5.4 are the same. Please check.
- [x] Chapter 5.4.5. Process for Reliability modelling - Step 5 - correct Log-Normal  XXX by Log-Normal (m,sigma )
- [x] ~Check mobile functionality. Presently, equations are not displayed properly in the mobile version (maybe too tong?)~ This was moved to #25.
- [x] Check references to (search for Part I and Part II). These Parts are not yet included - need to be done later.
- [x] Figure 5.2 and Note above contains references to chapters (e.g. MIS-1 refers to the old chapters) We need to correct the links - or to create an interactive version of this figure. 
- [x] Chapter 5.4.5. Process for Reliability modelling - Step 5 Model 3 - correct missing reference
- [x] Figure 5.5 - 5.7 might be candidates for interactive models.
- [x] Chapter 5.4.5. Process for Reliability modelling - Step 6 - correct missing reference
- [x] Chapter 5.4.5. Process for Reliability modelling - Step 7 - correct missing reference
- [x] Chapter 5.5 - Conclusions missing
- [x] #28

**Comment by MatthiasSchubert** [comment]
This is @MatthiasSchubert's review of the miscellaneous chapter:

- [ ] Check mobile functionality. Presently, equations are not displayed properly in the mobile version (maybe too tong?)
- [ ] Check references to (Part I and Part II). These are not yet included.
- [ ] Consider to change the color of the tables to a blueish color (color language should be consistent)

**Comment by csxADS** [comment]
First changes commit d1931c7ae11e758b52e06a8bae640753217462c5

**Comment by csxADS** [comment]
Statistical data in commit 9ffd2fc05d027515745387b769437df2655b048c

**Comment by csxADS** [comment]
Added bullet points commit d289f67beb47c8285ab29bc286377ee3c26ae182

**Comment by csxADS** [comment]
https://nrpmhandbook.reliability.space/system/handbook/reliability_prediction/system_level_modelling_wear_out.html#equation-equation-7-103

**Comment by paulremo** [comment]
> https://nrpmhandbook.reliability.space/system/handbook/reliability_prediction/system_level_modelling_wear_out.html#equation-equation-7-103

This equation is too long and can be rewritten to something more compact easily. Just change:
```
R_{k}\left( t \right) = e^{\left\lbrack - \left( \lambda_{k}t + \left( \frac{T_{\text{Ck} - 1} + t}{\alpha_{k}} \right)^{\beta_{k}} \right) \right\rbrack} \bullet e^{\left\lbrack - \left( \sum_{i = 1}^{i = k - 1}{\lambda_{i}T_{i}} \right) \right\rbrack} \bullet e^{\left\lbrack - \left( \sum_{i = 1}^{i = k - 1}\left( \frac{T_{\text{Ci}}}{\alpha_{i}} \right)^{\beta_{i}} \right) \right\rbrack}
```
to 
```
R_{k}\left( t \right) = e^{\left\lbrack - \left( \lambda_{k}t + \left( \frac{T_{\text{Ck} - 1} + t}{\alpha_{k}} \right)^{\beta_{k}} \right)  - \left( \sum_{i = 1}^{i = k - 1}{\lambda_{i}T_{i}} \right) - \left( \sum_{i = 1}^{i = k - 1}\left( \frac{T_{\text{Ci}}}{\alpha_{i}} \right)^{\beta_{i}} \right) \right\rbrack}
```
The product of exponentials is equal to the exponential of the sum of their arguments. In this case, I would actually not use the `e^{x}` notation, but opt for `\exp(x)` because the argument (`x`) in this case becomes very hard to read otherwise.

**Comment by csxADS** [comment]
Ok for this one but other equations are affected, and when we check the mobile version, almost all equations are displayed the wrong way. I don't think we can modify each formula

**Comment by csxADS** [comment]
@paulremo  For information \dot gives 
![image](https://user-images.githubusercontent.com/102167220/168759811-f6a92481-6e68-4906-82de-5b3a01e98d53.png)

which is not the same as \bullet

**Comment by csxADS** [comment]
I found that I should use \cdot

**Comment by csxADS** [comment]
@paulremo issue with url in bibtex library => displayed if we add "\usepackage{url}" to Bibtex style but I don't know where to find it

**Comment by csxADS** [comment]
Almost everything done, miss the table 5.3 but not sure it's possible

**Comment by paulremo** [comment]
The issue pertains to the table on [this page](https://nrpmhandbook.reliability.space/en/latest/miscellaneous/handbook/reliability_prediction/root_causes_coverage.html).

**Comment by csxADS** [comment]
DONE
