### ISSUE TITLE
Link broken in solid lubricant wear model

### ISSUE THREAD

**Issue by paulremo** [paulremo/NRPMHandbook#17]
The button *Go to handbook* on [this page](https://nrpmhandbook.reliability.space/mechanical/models/solid_lubricant_wear.html) is broken and does not link to a valid page.

**Comment by csxADS** [comment]
Fixed commit 1aa517ab8d45652e4afdb886dff7e388da482b7b

**Comment by paulremo** [comment]
Great! Thanks
