### ISSUE TITLE
Link glossary terms inside handbook

### ISSUE THREAD

**Issue by paulremo** [paulremo/NRPMHandbook#18]
There exists a glossary on the [handbook main page](http://nrpmhandbook.reliability.space/) that was updated in f5b5e671ce2c69921d4eea9bfde53fc2b788094f. The acronyms in the glossary should be linked throughout the digital handbook using the following syntax:

`` {term}`EEE` ``

**Comment by csxADS** [comment]
@paulremo I started this point yesterday so I have to go on this one to check that I did not break anything. One annoying thing is that the terms in the glossary are written in uppercase and are never in plural, so when I refer to it in the text it looks like this : CONTRIBUTING FACTORs. It's not that pretty, do you have an idea of how to change how the reference is displayed ?

**Comment by csxADS** [comment]
Done for miscellaneous commit 467ca097b0700b9bb0bd054a21264abedcf9a935

**Comment by paulremo** [comment]
It looks like the linking is done - I'm creating a new issue for the stylistic question that you asked. We should discuss at the next meeting.

**Comment by csxADS** [comment]
Done for all files 0c2ee56860ec6d7b9925f04a8c256c3b6ed55217
