### ISSUE TITLE
Update book homepage

### ISSUE THREAD

**Issue by paulremo** [paulremo/NRPMHandbook#19]
Update the [homepage of the book](https://nrpmhandbook.reliability.space/intro.html) by including the content from _New Reliability Prediction Methodology Aimed at Space Applications Reliability prediction handbook for space applications_. The document can be found [here](https://github.com/paulremo/NRPMHandbook/tree/main/01_Resources/handbook).

**Comment by csxADS** [comment]
Done commit f35e523832f04b69d5cf4a9f268e2b64fc66537b

**Comment by paulremo** [comment]
Great! I found the following issues:

- [ ] Remove mentions of *part* and instead reference directly the respective chapters (There are no more parts in the digital version of the handbook).
- [ ] Check if references are still needed in the digital handbook - none of the listed references are used in the introduction chapter.

**Comment by csxADS** [comment]
Done commit 04eca8d70bbbb408aa8a9f4f4ea0b99d1caf87f8

**Comment by paulremo** [comment]
To finalize this, please update the *Terms, definitions and abbreviations* page [here](https://nrpmhandbook.reliability.space/en/latest/miscellaneous/handbook/terms.html) by moving the glossary terms referenced in the miscellaneous section to this page.

**Comment by csxADS** [comment]
Done commit 328cb8c3e9c0741f7692d088d8a5cecbbd8f39aa

**Comment by paulremo** [comment]
Thanks! Closing it now 👍
