### ISSUE TITLE
Cursor does not change to hand on image links

### ISSUE THREAD

**Issue by paulremo** [paulremo/NRPMHandbook#2]
Cursor does not change to hand when hovering over image links to chapters on https://nrpmhandbook.reliability.space/intro.html.

**Comment by paulremo** [comment]
@csxADS - did you fix this? It seems to work now 😃. If so - just say at which commit you fixed it and close this ticket.

**Comment by csxADS** [comment]
Solved on commit [syst table 4 21](https://github.com/paulremo/NRPMHandbook/commit/2f9a58d1f65f74f0aae70c99978546825aff8c91)
