### ISSUE TITLE
Add methods chapter

### ISSUE THREAD

**Issue by paulremo** [paulremo/NRPMHandbook#21]
Add a chapter _Methods_ to the digital handbook by using _Part II_ of the _New Reliability Prediction Methodology Aimed at Space Applications Reliability prediction handbook for space applications_. This chapter will be the second chapter after the _Methodologies_ chapter and before the _EEE_ chapter. The document can be found [here](https://github.com/paulremo/NRPMHandbook/tree/main/01_Resources/handbook).

**Comment by csxADS** [comment]
Done commit 8ce6fbce18bac239fd1c5a165cc744b56a0b31f5

**Comment by paulremo** [comment]
Thanks! Also for the icon 😃
