### ISSUE TITLE
Remove duplicate images

### ISSUE THREAD

**Issue by paulremo** [paulremo/NRPMHandbook#24]
Pictures should only occur once on the repository. Currently, there are duplicate images on:
`02_NRPMHandbook\pictures`
and
`02_NRPMHandbook\_static\images`

Remove duplicate images from the `_static\images` folder.

**Comment by csxADS** [comment]
Done commit a7d5224e09f7f0d262d4fc5348728e680de369f0

**Comment by paulremo** [comment]
Thank you!

**Comment by paulremo** [comment]
Apparently, since a7d5224e09f7f0d262d4fc5348728e680de369f0 the logo is gone from the main page. I think this can be fixed by changing a wrong path inside the `_config.yml` file. 

@csxADS please have a look and let me know.

**Comment by csxADS** [comment]
Done commit 8ce6fbce18bac239fd1c5a165cc744b56a0b31f5

**Comment by paulremo** [comment]
Thanks!
