### ISSUE TITLE
Terms and definitions capitalization

### ISSUE THREAD

**Issue by paulremo** [paulremo/NRPMHandbook#26]
The terms and definitions in the original handbook were capitalized (e.g., CONTRIBUTING FACTOR). This is problematic when references are generated to terms throughout the book automatically because capitalized terms have ugly plurals (e.g., CONTRIBUTING FACTORs). 

The following things should be done:

- [x] Capitalize **only first letter** of every term (e.g. *Contributing factor*) in the glossary environment inside `terms.md`;
- [x] Transfer terms from Stephanie's latest version of the Miscellaneous chapter to the digital version;
- [x] Use lowercase for the beginning of each term definition;
- [x] For linking the terms inside the main text use the following syntax ``{term}`contributing factor<Contributing factor>` `` (you are free to stick to the standard capitalization rules for `contributing factor` but stick with the capitalization used in the glossary for the text `<Contributing factor>` 

**Attention**:
- Don't put the `{term}` role in titles (neither for abbreviations nor for terms and definitions)- only use it in the standard text

@csxADS: Be careful when automatically changing text in multiple documents. For example, failure models on [this page](https://nrpmhandbook.reliability.space/en/latest/mechanical/handbook/reliability_prediction/structural_models_equations.html#solid_lubricant_button) was changed to FAILURE MODEls (mode is not a model)!

**Comment by paulremo** [comment]
Rewrite the existing terms and definitions to stick to the *new convention*:

- First letters of terms and definitions should be capitalized (e.g. Contributing Factor)
- Don't put the `{term}` role in titles (neither for abbreviations nor for terms and definitions)- only use it in the standard text

@csxADS: Be careful when automatically changing text in multiple documents. For example, failure models on [this page](https://nrpmhandbook.reliability.space/en/latest/mechanical/handbook/reliability_prediction/structural_models_equations.html#solid_lubricant_button) was changed to FAILURE MODEls (mode is not a model)!

**Comment by csxADS** [comment]
@paulremo do I really need to change the capitalization inside terms.md ? That means I have to refactor each reference as well. It takes a very long time for not a big deal, isn't it ?

**Comment by paulremo** [comment]
Changing the capitalization inside `terms.md` should be really quick - and for the references in the rest of the document you can just do a (case-sensitive!) search and replace. That should be very quick, no?

**Comment by csxADS** [comment]
I'll do my best

**Comment by paulremo** [comment]
Great!
