### ISSUE TITLE
Review interactive python models

### ISSUE THREAD

**Issue by paulremo** [paulremo/NRPMHandbook#27]
Review the text in the interactive python models. They are fully functional, but the text needs to be updated and equations beautified/checked. Also, the output should contain a reference to the failure time where possible (e.g., number of cycles until failure etc.).

**Comment by paulremo** [comment]
I prepared a draft of the three models. Please have a look and let me know if I should change anything.

**Comment by MatthiasSchubert** [comment]
Review of models finalized. @me: need to check the range of inputs for the fluid lubricant wear.
