### ISSUE TITLE
Turn Table 5.3 into static table

### ISSUE THREAD

**Issue by paulremo** [paulremo/NRPMHandbook#28]
Turn the table on [this page](https://nrpmhandbook.reliability.space/en/latest/miscellaneous/handbook/reliability_prediction/root_causes_coverage.html) 
 into a static table (delete html) to allow automatic linking to a specific section. Then change 
 "Considered by the process described in Section 11.5 (Wear-Out modelling)" 
 to
 "Considered by the process described in Section 11.5". (automatic link)

Have a look at the jupyter book manual for instructions on how to create Myst tables [here](https://jupyterbook.org/en/stable/reference/cheatsheet.html?highlight=list-table#tables)

**Comment by csxADS** [comment]
done

**Comment by paulremo** [comment]
Closed! Note the `widths` directive I added to adjust the relative table widths.
