### ISSUE TITLE
Iframes too high

### ISSUE THREAD

**Issue by paulremo** [paulremo/NRPMHandbook#3]
Iframes get resized to the window height on reloading the page. They should automatically resize to the content height.

**Possible cause**
This issue could be related to the \02_NRPMHandbook\_static\js\resize_iframe.js function that is responsible for dynamically setting the iFrame height.

**Comment by paulremo** [comment]
This was fixed for a single page (`miscellaneous\handbook\rp\reliability_data_sm.md`) in dbd7e23f065047728f45b96ea5f1e46e09f46fe8.

The fix reverts back to using the onload event of the iframe tag but passes the calling object with `onload="resize_iframe(this)"`. 

Attention: This does not work on localhost (at least in Chrome) but works fine on the webserver. To test it locally, use a local web-server (e.g.,  [this](https://stackoverflow.com/questions/18586921/how-to-launch-html-using-chrome-at-allow-file-access-from-files-mode).

@csxADS please propagate the changes from `miscellaneous\handbook\rp\reliability_data_sm.md` to all other included iframes.

**Comment by csxADS** [comment]
All iframes updated
