### ISSUE TITLE
Glossary terms must be preceded by empty line

### ISSUE THREAD

**Issue by paulremo** [paulremo/NRPMHandbook#31]
Add an empty line before every element inside the glossary directive (this concerns only the acronyms) on [this page](https://nrpmhandbook.reliability.space/en/latest/miscellaneous/handbook/terms.html).

**Comment by csxADS** [comment]
Done

**Comment by paulremo** [comment]
Thanks! There is still a minor typo/wrong empty lines 501 and 516.  I don't want to edit the file while you're working on it so I let you take care of it.

**Comment by csxADS** [comment]
Done

**Comment by paulremo** [comment]
Great! Thanks 😃
