### ISSUE TITLE
Move searchable tables to jupyter book source

### ISSUE THREAD

**Issue by paulremo** [paulremo/NRPMHandbook#39]
Searchable tables are currently embedded with iframes as external HTML pages. This works for the web version of the digital handbook but it is problematic for two reasons:

1. Content is not searchable from the central search feature;
2. Tables do not show up when document is compiled with LaTeX.

It is, therefore, suggested to transform the existing tables into standard `.md` tables and connect the `table_search.js` to the to the HTML tables generated by jupyter-book.

From a quick inspection of the tables that jupyter book creates (e.g., table on [this page](https://nrpmhandbook.reliability.space/en/latest/mechanical/models/solid_lubricant_wear.html)), this should be possible. 

I think the necessary steps to make this work would be:

1. transform the existing html tables to reStructured tables and include them directly in the `.md` source. Transformation is possible [here](https://tableconvert.com/html-to-restructuredtext). This might need some manual tweaking because we ultimately require `list-tables` to allow formatting (e.g., different relative column widths);
2. give each table a unique name, e.g., `my-table-12314` (**ATTENTION:** don't use underscore in name, [instructions](https://docutils.sourceforge.io/docs/ref/rst/directives.html));
3. rewrite the `searchTable` function inside `table_search.js` to accept a target table argument
4. Include only the source code for the input field directly above the `list-tables` directive (`<input type="text" class="myInput" id="myInput" onkeyup="searchTableJupyter(this, `my-table-12314`)" placeholder="Search table...">`)

@csxADS: Do you think this is feasible?

**Comment by paulremo** [comment]
A working test was commited in bb9de59c95330d4699a15835a6b7f740fa6dd134.

**Comment by paulremo** [comment]
The source of all searchable tables should be moved to the jupyter book `.md` source files.

**Comment by csxADS** [comment]
Done during refactoring

**Comment by paulremo** [comment]
Thanks!
