### ISSUE TITLE
Broken links in guide

### ISSUE THREAD

**Issue by paulremo** [paulremo/NRPMHandbook#40]
The links in the [guide on this page](https://nrpmhandbook.reliability.space/en/latest/miscellaneous/models/reliability_guide.html) are broken.

**Comment by paulremo** [comment]
You are right...damn iframes...

I just checked and there are three remaining iframes in the handbook (inside `method_selection.md`, `failure_rate_processing.md`, and `reliability_guide.md`). Do you think we could get rid of iframes completely by just including the javascript in the page directly? Anyways, the iframe HTML pages are mostly empty - so I think it should be feasible.

If I'm not mistaken, this could be achieved by replacing 
```
<iframe class="ext_content" src="../../../_static/interactivity/html/decision_tree2.html" frameborder="0" onload="resize_iframe(this)"></iframe>
```
with
```
<canvas id="canvas" width="800" height="800"></canvas>
```

I think this should work because all `.js` files inside the `_static` folder are automatically linked to all HTML pages. This includes the relevant `\_static\interactivity\js\decision_tree2.js` in this case.

Let me know!

**Comment by csxADS** [comment]
Do you want to include row html inside the canvas ?

**Comment by csxADS** [comment]
@paulremo I have to change the js script because the script is executed before the HTML element are loaded in the document. Thus it takes more time than expected

**Comment by csxADS** [comment]
@paulremo the way I coded the guide is not compatible with including direct html inside markdown. I can try to modify it but it will take time

**Comment by paulremo** [comment]
Okay, then leave it like it is now - but for new models implement them in a markdown-compatible way.

**Comment by csxADS** [comment]
I managed to refactor the guide correctly to fit the markdown file. That's good news since it's the only one with links ! I'm taking care of the decision tree, maybe I'll have to refactor it as well

**Comment by paulremo** [comment]
Great! Looks very good!
