### ISSUE TITLE
Spaces in labels

### ISSUE THREAD

**Issue by paulremo** [paulremo/NRPMHandbook#52]
Throughout the handbook labels are defined with spaces (e.g., `:label: Equation Method 7.45`). This is not an issue when compiling the book as a website, however, it is problematic for two reasons:

- it is bad practice because it reduces the source-code readability
- it causes erros in the LaTeX compiler (#38)

It is therefore suggested to replace all labels with single words, e.g. replace
```
:label: Equation Method 7.45
```
with
```
:label: eq_method_7.45
```

**Comment by paulremo** [comment]
Reopening this, because the issue is fixed in *mechanical* but persists in other chapters.

**Comment by csxADS** [comment]
Remains method & methodology

**Comment by paulremo** [comment]
Looks good!
