### ISSUE TITLE
Duplicate labels

### ISSUE THREAD

**Issue by paulremo** [paulremo/NRPMHandbook#55]
Throughout the handbook, duplicate labels are assigned to figures, tables, and equations. As an example, the following defines two different labels for the same object (`syst_equation4_26` and `Equation_7_26`):
`````
(syst_equation4_26)=
````{admonition} Equation
:class: equation
``
``  
```{math}
:label: Equation_7_26
P\left(B=S_{B_{1}}\right) = P\left(B=S_{B_{1}}|A=S_{A_{1}}\right)P\left(A=S_{A_{1}}\right) + P\left(B=S_{B_{1}}|A=S_{A_{2}}\right)P\left(A=S_{A_{2}}\right)
```
````
`````

This practice is confusing and creates problems in the LaTeX typesetting (#38). As a fix, the label should only be defined inside the equation, i.e. remove the `(syst_equation4_26)=` and check that all references to `syst_equation4_26` are replaced with `Equation_7_26`.

To find ocurrences of this, you can search for the following regex: `=\r\n``` `

**Comment by csxADS** [comment]
@paulremo Can you confirm there's no duplicate label issues anymore ?
