### ISSUE TITLE
Reformat homepage icons

### ISSUE THREAD

**Issue by paulremo** [paulremo/NRPMHandbook#60]
**Description**
In the homepage icons can be found with hyper-links to the various chapters (e.g. methodologies, methods, etc.) and only below the group of icons can an explanation be found on them. The automatic response for a user is to go directly to the icon to look for the information without having scrolled down before to search for the information.

**Fix**
![image](https://user-images.githubusercontent.com/100701926/174795347-e964e57a-b290-4833-8304-9a358d88a09b.png)

**Comment by csxADS** [comment]
@paulremo I found the text for methods and methodologies in the following paragraphs but what text do I write for EEE, mechanical, miscellaneous and system ?
