### ISSUE TITLE
Expand acronym description below certain figures

### ISSUE THREAD

**Issue by paulremo** [paulremo/NRPMHandbook#62]
On [this page](https://nrpmhandbook.reliability.space/en/latest/miscellaneous/handbook/reliability_prediction/basic_fr_derivation_nsm.html) there exist some weirdly placed abbreviations that should be explained. Particularly:

- [x] After [Fig. 9.8](https://nrpmhandbook.reliability.space/en/latest/miscellaneous/handbook/reliability_prediction/basic_fr_derivation_nsm.html#figure-5-8) there is a list of three acronyms ([SEV](https://nrpmhandbook.reliability.space/en/latest/miscellaneous/handbook/terms.html#term-SEV)erity, [OCC](https://nrpmhandbook.reliability.space/en/latest/miscellaneous/handbook/terms.html#term-OCC)urrence, [DET](https://nrpmhandbook.reliability.space/en/latest/miscellaneous/handbook/terms.html#term-DET)ectability). These should be explained differently by first giving the full word and then placing the acronym in parenthesis after the word (e.g., severity (SEV).
- [x] After [Fig. 9.9](https://nrpmhandbook.reliability.space/en/latest/miscellaneous/handbook/reliability_prediction/basic_fr_derivation_nsm.html#figure-5-9) a list of four acronyms is given. They should be explained in the caption of the figure by listing the full word first and giving the acronym in parenthesis later.
- [x] After [Table 9.6](https://nrpmhandbook.reliability.space/en/latest/miscellaneous/handbook/reliability_prediction/basic_fr_derivation_nsm.html#misc-table4-6) an acronym is given. The acronym should be moved to the table caption and be explained by listing the full word first and giving the acronym in parenthesis later.

**Comment by csxADS** [comment]
@paulremo  What do you by "to the table caption" ? Do you want to put it inside the table ?

**Comment by paulremo** [comment]
The _table caption_ is the descriptive text following each table. Is it possible to put the references there?

**Comment by csxADS** [comment]
I can do this for figures but not for tables 
![image](https://user-images.githubusercontent.com/102167220/174801557-0d6eafd2-eda4-41ca-864c-6ee0af8199de.png)

**Comment by paulremo** [comment]
Just to be clear: you don't have to put the bullet points to the captions, just the terms and their acronyms. You could just add the sentence. _The following terms are mentioned in this figure: solar array (SA), ..._

Or are you telling me that it is not possible to use the `{term}` role in table captions?

**Comment by csxADS** [comment]
Yes I can but I can only Put 1 sentence, do I put the following sentence as a caption : "Table 9.6 Occurrence scale with 10 levels. The following terms are mentioned in this figure: solar array (SA), ..." ?

**Comment by paulremo** [comment]
Yes that is fine! Captions are always a single sentence...sorry for the confusion 😃.

**Comment by csxADS** [comment]
@paulremo  it breaks the list-table admonition while using term reference syntax, is there another way to reference to glossary terms (not using {term}}`...`)?

**Comment by paulremo** [comment]
I don't think so...but why don't you transform the table image to a proper table (list-table) and place the TRL links directly inside the table? This way you also don't have to reference it in the table caption.

**Comment by csxADS** [comment]
I could but we will lose the colors on the second table.

**Comment by paulremo** [comment]
Yes, I see...I still think it's a trade-off, because the table is currently not searchable and the information inside is hard to track if it is just given as an image. But let's not get lost on this detail, I suggest you just add TRL to the caption without referencing it:

_Occurrence scale with 10 levels and the associated technology readiness level (TRL)_
