### ISSUE TITLE
The astronaut in failure rate processing is not visible in certain screen sizes.

### ISSUE THREAD

**Issue by paulremo** [paulremo/NRPMHandbook#68]
Make the astronaut in [10.1. Failure rate processing](https://nrpmhandbook.reliability.space/en/latest/miscellaneous/models/failure_rate_processing.html) visible on all screen sizes. This is related to #25.

Another option would be to add short tooltips (e.g., a couple of words as the gist of the text displayed by the astronaut)

**Comment by paulremo** [comment]
@csxADS will modify the astronaut message to stick to the top of the page when scrolling. The automatic height adjustment of the iframe (#3) will have to be disabled on this page to accommodate this.

**Comment by csxADS** [comment]
Done but can't see results

**Comment by paulremo** [comment]
What do you mean? Can you be a bit more specific?

**Comment by csxADS** [comment]
The files are up to date in NRPMInteractivity but the website still displays the previous interface

**Comment by csxADS** [comment]
You can set the css property "overflow-y: hidden" to the iframe, it should work

**Comment by csxADS** [comment]
overflow-x *

**Comment by paulremo** [comment]
@csxADS did you fix this? I see that you modified something in a27466f9c70b8f964846e10f6c6a8e13ded36ee8, but the vertical scrollbar is still visible.

**Comment by paulremo** [comment]
Done! Thanks :)
