### ISSUE TITLE
Background color does not show in pdf of "failure rate processing"

### ISSUE THREAD

**Issue by paulremo** [paulremo/NRPMHandbook#69]
This is a strange bug...when clicking the "print pdf" button on [10.1. Failure rate processing](https://nrpmhandbook.reliability.space/en/latest/miscellaneous/models/failure_rate_processing.html#) the background colours of all fields disappear...do you have any idea why this is happening?

**Comment by csxADS** [comment]
It works on Firefox, it's doesn't work on Chrome

**Comment by csxADS** [comment]
Yes I caught this one but it uses the body tag which is not used for now. I'll try something but I can't say if it will work

**Comment by paulremo** [comment]
Don't spend too much time on it - if it doesn't work right away we postpone it.

**Comment by csxADS** [comment]
On chrome you just have to click the check the "Background graphics" option when printing
![image](https://user-images.githubusercontent.com/102167220/174811396-b0838173-16db-4511-9106-3c71ab4a6798.png)

**Comment by paulremo** [comment]
Alright - good enough for me! Thanks 😃
