### ISSUE TITLE
create an interactive model for the systems chapter

### ISSUE THREAD

**Issue by paulremo** [paulremo/NRPMHandbook#73]
Make an interactive model for models 1,2, and 3 described [here](https://nrpmhandbook.reliability.space/en/latest/system/handbook/reliability_prediction/system_level_modelling_wear_out.html).

**Comment by paulremo** [comment]
There exists now a draft of this interactive model [here](https://nrpmhandbook.reliability.space/en/latest/system/models/wear_out.html).

There is one issue with the model: the way Models 2 and 3 are described [here](https://nrpmhandbook.reliability.space/en/latest/system/handbook/reliability_prediction/system_level_modelling_wear_out.html), the failure rate is infinity at the transition point where t=tau, if beta < 1. Two possible fixes:

- Allow only beta > 1 (currently implemented)
- Change the model definition to assume time-invariant lambdas for t <= tau instead of t < tau

**Comment by csxADS** [comment]
Same as #65

**Comment by paulremo** [comment]
Addressed in https://github.com/paulremo/NRPMInteractivity/issues/5
