### ISSUE TITLE
Change numbering and referencing in figures, equations, tables, and sections to auto

### ISSUE THREAD

**Issue by csxADS** [paulremo/NRPMHandbook#8]

**Comment by paulremo** [comment]
Currently, all figures, equations, and tables are numbered and referenced manually. This is cumbersome, error-prone, and will lead to problems when new equations are inserted into the digital handbook in the future. We will therefore switch to automatic numbering and references wherever possible. Therefore, figures, tables, and equations should be inserted and referenced in the document in the following way:

### Note

- It shouldn't be necessary to use target headers (i.e., `(target_header)=` ) for any auto-numbered items.
- The number used in the `name` or `label` field will not be displayed to the user and is only important for internal reference.
- References inside titles (or captions) are **not permitted**!


### Figures 
- **Insertion**
````
```{figure} ../../pictures/figure4_1.png
---
width: 600px
name: misc_fig_4_1
---
Failure rate as a function of time for typical mechanical components.
```
````
- **Reference**
`` {numref}`misc_fig_4_1` `` 

### Tables
- **Insertion** (standard tables)
````
```{list-table}
:header-rows: 1
:name: misc_table_4_8

* - Col1
  - Col2
* - Row1 under Col1
  - Row1 under Col2
* - Row2 under Col1
  - Row2 under Col2
```
````
- **Insertion** (interactive tables)
````
```{list-table} Some interactive table title
:class: interactive-table
:name: misc_table_4_8

* - <iframe class="ext_content" src="../../../_static/interactivity/html/misc_table4_8.html" frameBorder="0" onload="resize_iframe(this)" ></iframe>
```
````
- **Reference**
`` {numref}`misc_table_4_8` `` 

### Equations
As it is not possible to automatically number admonition tiles, I suggest **not to use equations inside admonitions** extensively. Instead, the equation admonition class should be used to highlight certain important equations and then give them a meaningful title.

- **Insertion** (equation outside admonition)
````
```{math}
:label: misc_eq_14
w_{t+1} = (1 + r_{t+1}) s(w_t) + y_{t+1}
```
````
- **Insertion** (equation inside admonition)
`````
````{admonition} {eq}`misc_eq_14`
:class: equation
``
``  
```{math}
:label: misc_eq_14
R_{S}(t) = R_{A}(t) * R_{B}(t)
```
````
`````
- **Reference**
`` Eq. {eq}`misc_eq_14` ``

**Comment by csxADS** [comment]
Changed all figure references (77 in 16 files)

**Comment by paulremo** [comment]
Yes! You're right - I actually mentioned this right below the Equation section. You can't put references in titles/captions - we'll have to find a different way to do this 😄.

How about the following (to also summarize successive equations in one admonition):
`````
````{admonition} Equation description
:class: equation
``
``  
```{math}
:label: misc_eq_14
R_{S}(t) = R_{A}(t) * R_{B}(t)
```
```{math}
:label: misc_eq_15
R_{S}(t) = R_{A}(t) * R_{B}(t)
```
```{math}
:label: misc_eq_16
R_{S}(t) = R_{A}(t) * R_{B}(t)
```
````
`````
Can you test it?

**Comment by csxADS** [comment]
You mean removing the reference in the title and only put "Equation" instead ?

**Comment by paulremo** [comment]
Yes, either "Equation" or some meaningful two-word description of what the equation shows. The number should be shown automatically inside brackets next to the equation.

**Comment by csxADS** [comment]
Done for tables miscellaneous, it will be very long for titles

**Comment by paulremo** [comment]
It will save a lot of time down the line 😄. 

As I mentioned in the main note above, this will not work for H3 sections (###). For those sections, leave the current manual reference, but remove the number, i.e., change:
```
[Section 4.4.1](misc_4_4_1)
```
to anything that matches the sentence
```
as discussed in the [standard model section](misc_4_4_1)
```

**Comment by csxADS** [comment]
Seems that it does not work for section titles

(Reliability Models for miscellaneous items)=
# Reliability Models for miscellaneous items

appears like 

(Reliability Models for miscellaneous items)=
5.4.4. Reliability Models for miscellaneous items

What about keeping [...](...) for all titles using the explicit title instead of the numbering ?

**Comment by csxADS** [comment]
Found the issue

**Comment by csxADS** [comment]
Done commit 27b52b99bfdce5534d8eba33756a6110b471a39f

**Comment by paulremo** [comment]
Thanks for that! It looks like you changed the hierarchy of certain sections - is that correct? If so, we should discuss this at today's meeting.

**Comment by csxADS** [comment]
There was just titles using too much # so that the build did not take it into account. That was a mistake during the copy of texts so I just removed useless #

**Comment by paulremo** [comment]
Okay, great! Did you take care of this in all chapters or just Miscellaneous?

**Comment by csxADS** [comment]
No but shouldn't we wait for the final decision to be taken on this subject ?

**Comment by paulremo** [comment]
@csxADS is this issue addressed for the Miscellaneous chapter?

**Comment by csxADS** [comment]
I'll have a check this morning and I keep you updated as soon as possible !

**Comment by csxADS** [comment]
Everything seems to be ok for miscellaneous @paulremo

**Comment by paulremo** [comment]
Thanks! I'll close this issue then.
