### ISSUE TITLE
Missing examples in mechanical chapter

### ISSUE THREAD

**Issue by paulremo** [paulremo/NRPMHandbook#84]
The [examples section](https://nrpmhandbook.reliability.space/en/latest/mechanical/handbook/reliability_prediction/examples.html) of the mechanical chapter is empty. Content from the classic version is missing here.

**Comment by paulremo** [comment]
@csxADS I prepared the section, please review it and close this ticket.

**Comment by csxADS** [comment]
Here are my comments :

- on table 5.4.21 (https://nrpmhandbook.reliability.space/en/latest/mechanical/handbook/reliability_prediction/examples.html#meca-examples-table-3) it seems that you didn't configure the header
- same for 5.4.20
- you did not encapsulate the equations into admonitions
- you forgot to attribute a label to the third title (Updating of structural reliability methods using right censored data)
That's all I noticed
