### ISSUE TITLE
Finish EEE annexes

### ISSUE THREAD

**Issue by paulremo** [paulremo/NRPMHandbook#88]
Finish the three missing EEE annexes:

- [x] [Annex A](https://nrpmhandbook.reliability.space/en/latest/eee/handbook/annex_a.html)
- [x] [Annex B](https://nrpmhandbook.reliability.space/en/latest/eee/handbook/annex_b.html)
- [x] [Annex C](https://nrpmhandbook.reliability.space/en/latest/eee/handbook/annex_c.html)

**Comment by csxADS** [comment]
Done
