### ISSUE TITLE
Tables in list-table not full width

### ISSUE THREAD

**Issue by paulremo** [paulremo/NRPMHandbook#9]
Interactive tables embedded inside `list-table` environments (see also #8) only span 50% of the page width. They should span the whole page width.

**Comment by paulremo** [comment]
A fix was committed in 6f74b38f693c03e28d7f9599966374e92f3abdf6. However, this fix is not ideal because:

- We don't really know why the following CSS snippet fixes the issue by forcing the `col`-tag width to 1%. This might cause problems in the future:
```
.interactive-table col {
	width: 1% !important;
}
```
- It uses the CSS `!important` modifier that is not recommended

**Comment by paulremo** [comment]
The recent refactoring of all external tables to the source (#39) made the `interactive-table` style obsolete. 

@csxADS: Please confirm that the style is indeed not used anymore and close this ticket.

**Comment by csxADS** [comment]
I confirm
